targets = {
  "ubuntu12"  => {
    "box" => "ubuntu/precise64"
  },
  "ubuntu14"  => {
    "box" => "ubuntu/trusty64"
  },
  "ubuntu16"  => {
    "box" => "ubuntu/xenial64"
  }
}

Vagrant.configure("2") do |config|
  
  # configure network ports
  config.vm.network :forwarded_port, host: 9200, guest: 9200 # Elasticsearch
  config.vm.network :forwarded_port, host: 9300, guest: 9300 # Logtash
  config.vm.network :forwarded_port, guest: 5601, host: 5601 # Kibana
  
  config.vm.provider "virtualbox" do |v|
    if ENV['OSQUERY_BUILD_CPUS']
      v.cpus = ENV['OSQUERY_BUILD_CPUS'].to_i
    else
      v.cpus = 1
    end
    v.memory = 2048
  end

  targets.each do |name, target|
    box = target["box"]
    config.vm.define name do |build|
      build.vm.box = box
      build.vm.provision :shell, path: "./provision/#{name}/osquery.sh"
      build.vm.provision :shell, path: "./provision/#{name}/elk.sh"
      build.vm.provision :shell, path: "./provision/#{name}/elk_config.sh",
        env: {"OS_VER" => "#{name}"}
    end
  end
end
