# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # use the empty dummy box
    config.vm.box = "dummy"
    config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    # Use Virtualbox by default
    config.vm.provider "virtualbox"
    config.vm.provider "aws"
    
    # configure provisioning
    config.vm.provision "shell", path: "../provision/ubuntu16/osquery.sh"
    config.vm.provision "shell", path: "../provision/elk.sh"
    # config.vm.provision "shell", path: "../provision/elk_config.sh"
  
    # VirtualBox Provider-specific configuration
    config.vm.provider "virtualbox" do |vb, override|
    
        # set the name
        vb.name = "osquery-athena"

        # set the basebox to be Ubuntu 16.04 LTS
        # override.vm.box = "ubuntu/xenial64"
        #override.vm.box_url = "https://atlas.hashicorp.com/ubuntu/boxes/xenial64"
        override.vm.box = "geerlingguy/ubuntu1604"
        override.vm.box_url = "https://atlas.hashicorp.com/geerlingguy/boxes/ubuntu1604"
        
        # configure VM
        vb.cpus = 1
        vb.memory = 1024
        vb.gui = false
        
        # Share a folder to the guest VM, types: docker, nfs, rsync, smb, virtualbox
        # Windows supports: smb
        # Mac supports: rsync, nfs
        # override.vm.synced_folder host_folder.to_s, guest_folder.to_s, type: "smb"
        override.vm.synced_folder "../provision", "/vagrant"
        
        # Create a forwarded port mapping which allows access to a specific port
        # within the machine from a port on the host machine. In the example below,
        # accessing "localhost:8080" will access port 80 on the guest machine.
        override.vm.network "forwarded_port", host: 9300, guest: 9300 # Logtash
 
        # setup local apt-get cache
        # if Vagrant.has_plugin?("vagrant-cachier")
            # Configure cached packages to be shared between instances of the same base box.
            # More info on the "Usage" link above
            # override.cache.scope = :box
        # end
    
        # disable the vbguest update plugin
        if Vagrant.has_plugin?("vagrant-vbguest")
            override.vbguest.auto_update = true
        end
    end



    # configuration when deploying to Amazon
    config.vm.provider "aws" do |aws, override|
    
        # Load sensitive AWS credentials from external file, DO NOT save in Repo!!!
        # @see http://blog-osshive.rhcloud.com/2014/02/05/provisioning-aws-instances-with-vagrant/
        require 'yaml'
        aws_filepath = File.dirname(__FILE__) + "/../aws-config.yml"
        if File.exist?(aws_filepath)
            aws_config  = YAML.load_file(aws_filepath)["aws"]
        else
            print "Error: '" + aws_filepath + "' is missing...\n"
        end
        
        # set AWS creds
        aws.access_key_id             = aws_config["access_key_id"]
        aws.secret_access_key         = aws_config["secret_access_key"]
        aws.keypair_name              = aws_config["keypair_name"]
        
        # configure SSH... and fuck Windows file pathways...
        override.ssh.private_key_path = aws_config["pemfile"]
        override.ssh.username         = "ubuntu"

        # Ubuntu 16.04 Xenial 64-bit HVM
        # @see https://cloud-images.ubuntu.com/locator/ec2/
        aws.region = "us-east-1"
        aws.ami = "ami-2757f631"
            # ami-2657f630    amd64, ebs:ssd
            # ami-2757f631    amd64, HVM, ebs
            # ami-914ced87    amd64, HVM, instance-store
            # ami-dc40e1ca    amd64, instance-store
        
        # set instance settings
        # @see https://aws.amazon.com/ec2/instance-types/
        aws.instance_ready_timeout    = 180
        aws.instance_type             = "t2.micro"
        aws.associate_public_ip       = true
        aws.subnet_id                 = aws_config["subnet_id"]
        aws.tags = {
            'Name' => 'osquery-athena',
        }
        # use 40GB, because we like it UUGE!
        # @see http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html
        aws.block_device_mapping = [
            {
                'DeviceName' => '/dev/xvda',
                'VirtualName' => 'root',
                'Ebs.VolumeSize' => 40,
                'Ebs.DeleteOnTermination' => 'true'
            }
        ]

        # Configure file sharing using rsync.
        # This requires Windows users to have Cygwin or MinGW installed.
        # @see https://www.vagrantup.com/blog/feature-preview-vagrant-1-5-rsync.html
        # @see https://github.com/mitchellh/vagrant/blob/master/website/docs/source/v2/synced-folders/rsync.html.md
        override.vm.synced_folder "../../provision", "/vagrant", type: "rsync"
        override.vm.synced_folder "../../data/website", "/var/www/html/vinodiscover", type: "rsync"
        # , disabled: true
        # To continuously update files bi-directionally, open another shell, run:
        # "vagrant rsync-auto"
        
        # Fix for Windows users running Cygwin:
        if Vagrant::Util::Platform.windows?
            ENV["VAGRANT_DETECTED_OS"] = ENV["VAGRANT_DETECTED_OS"].to_s + " cygwin"
        end
    
        # disable the vbguest update plugin
        if Vagrant.has_plugin?("vagrant-vbguest")
            override.vbguest.auto_update = false
        end

        # run AWS specific steps
        override.vm.provision :shell, path: "../../provision/bootstrap_aws.sh",
          env: {"CONFIG_DIR" => "vino-aws-prod"}
    end
end
